export default {
    1: {
        id: "01",
        title: "",
        desc: "",
        color: "#FFFE34",
        icon: "",
    },
    2: {
        id: "02",
        title: "",
        desc: "",
        color: "#FFFE34",
        icon: "",
    },
    4: {
        id: "04",
        title: "",
        desc: "",
        color: "#FFFE34",
        icon: "",
    },
    6: {
        id: "06",
        title: "",
        desc: "",
        color: "#FFFE34",
        icon: "",
    },
    8: {
        id: "08",
        title: "",
        desc: "",
        color: "#FFFE34",
        icon: "",
    },
    10: {
        id: "10",
        title: "",
        desc: "",
        color: "#FFFE34",
        icon: "",
    },
    12: {
        id: "12",
        title: "",
        desc: "",
        color: "#FFFE34",
        icon: "",
    },
    14: {
        id: "14",
        title: "",
        desc: "",
        color: "#FFFE34",
        icon: "",
    },
    16: {
        id: "16",
        title: "",
        desc: "",
        color: "#FFFE34",
        icon: "",
    },
    18: {
        id: "18",
        title: "",
        desc: "",
        color: "#FFFE34",
        icon: "",
    },
    20: {
        id: "20",
        title: "",
        desc: "",
        color: "#FFFE34",
        icon: "",
    },
    22: {
        id: "22",
        title: "",
        desc: "",
        color: "#FFFE34",
        icon: "",
    },
    24: {
        id: "24",
        title: "",
        desc: "",
        color: "#FFFE34",
        icon: "",
    },
    26: {
        id: "26",
        title: "",
        desc: "",
        color: "#FFFE34",
        icon: "",
    },
    28: {
        id: "28",
        title: "",
        desc: "",
        color: "#FFFE34",
        icon: "",
    },
    30: {
        id: "30",
        title: "",
        desc: "",
        color: "#FFFE34",
        icon: "",
    },
    32: {
        id: "32",
        title: "",
        desc: "",
        color: "#FFFE34",
        icon: "",
    },
    34: {
        id: "34",
        title: "",
        desc: "",
        color: "#FFFE34",
        icon: "",
    },
    36: {
        id: "36",
        title: "",
        desc: "",
        color: "#FFFE34",
        icon: "",
    },
    38: {
        id: "38",
        title: "",
        desc: "",
        color: "#FFFE34",
        icon: "",
    },
    40: {
        id: "40",
        title: "",
        desc: "",
        color: "#FFFE34",
        icon: "",
    },
    42: {
        id: "42",
        title: "",
        desc: "",
        color: "#FFFE34",
        icon: "",
    },
    44: {
        id: "44",
        title: "",
        desc: "",
        color: "#FFFE34",
        icon: "",
    },
    46: {
        id: "46",
        title: "",
        desc: "",
        color: "#FFFE34",
        icon: "",
    },
    48: {
        id: "48",
        title: "",
        desc: "",
        color: "#FFFE34",
        icon: "",
    },
};
